# Generated by Django 5.2.7 on 2025-12-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_agency_documents_agency_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='agency',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='office_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='referreduser',
            name='case_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='referreduser',
            name='court_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='referreduser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingprovider',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainingprovider',
            name='experience',
            field=models.CharField(blank=True, default='', help_text='Years of experience or description', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingprovider',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
