# Generated by Django 5.2.7 on 2025-12-09 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_agency_address_alter_agency_agency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprovider',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
