# Generated by Django 5.2.7 on 2025-11-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='role',
            new_name='user_type',
        ),
    ]
